-- App User
CREATE SEQUENCE IF NOT EXISTS public.ID_SEQ_APP_USER INCREMENT 1 START 1;
CREATE TABLE IF NOT EXISTS public.APP_USER(
    ID INTEGER PRIMARY KEY
);
ALTER TABLE public.APP_USER ADD COLUMN NAME CHARACTER VARYING;
ALTER TABLE public.APP_USER ADD COLUMN USERNAME CHARACTER VARYING;
ALTER TABLE public.APP_USER ADD COLUMN PASSWORD CHARACTER VARYING;
ALTER TABLE public.APP_USER ADD COLUMN IS_ADMIN BOOLEAN;

-- Create admin user
CREATE OR REPLACE FUNCTION public.CREATE_ADMIN()
RETURNS VOID AS 
$BODY$
DECLARE _count INTEGER;
BEGIN
    SELECT COUNT(*) FROM public.APP_USER WHERE IS_ADMIN IS TRUE INTO _count;
    IF _count <= 0 THEN
        INSERT INTO public.APP_USER(ID, NAME, USERNAME, PASSWORD, IS_ADMIN) 
        VALUES(NEXTVAL('ID_SEQ_APP_USER'), 'Administrator', 'admin', '$2b$10$5Sjg4VPeE4v8oX8Wy.KUbetBDi.2NwIsZilkMBzRD1FpeDC7GZKPe', true);
    END IF;
END;
$BODY$ LANGUAGE plpgsql VOLATILE COST 100;
SELECT CREATE_ADMIN();